Update wg-add-client

diff --git a/wg-add-client b/wg-add-client
--- a/wg-add-client
+++ b/wg-add-client
@@ -35,7 +35,11 @@ echo "Copy config to /home/${linux_user}/${cust_name}-${1}.conf"
 cp /etc/wireguard/clients/$1/wg0.conf /home/${linux_user}/${cust_name}-${1}.conf
 chown ${linux_user}:${linux_user} /home/${linux_user}/${cust_name}-${1}.conf
 echo "Get the config via WinSCP"
+
 echo "Clients:"
 /usr/bin/wg-list-clients
-wg-quick down wg0 || echo "Stop service failed"
-wg-quick up wg0 || echo "Start service failed"
+
+echo "Restart wireguard:"
+systemctl restart wg-quick@wg0 && echo "restart completed" && exit 0
+echo "restart FAILED"
+exit 1
